[project]
name = "widb2-mcp"
version = "0.1.0"
description = "MCP Server Projekt"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "thws-lecture",
]
